package AdditionApp;


/**
* AdditionApp/AdditionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Addition.idl
* Saturday, 2 July, 2022 9:11:45 AM IST
*/

public interface AdditionOperations 
{
  int add (int a, int b);
  void shutdown ();
} // interface AdditionOperations
