package CalcApp;


/**
* CalcApp/Calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Calc.idl
* Saturday, 2 July, 2022 8:57:54 AM IST
*/

public interface Calc extends CalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calc
